# 画像の足し算
opencvで画像はnumpyの配列なので、足すとそのまま足される。

In [ ]:
import numpy as np
import cv2

x_image = np.uint8([100])
y_image = np.uint8([10])

x_image + y_image

array([110], dtype=uint8)

uint8になっているので、255を超えると0に戻る

In [23]:
x_image = np.uint8([250])
y_image = np.uint8([10])

x_image + y_image

array([4], dtype=uint8)

`cv.add()`を使うと、最大値の255で止まり、255を超えても0に戻らない。ただし、`dtype`を指定する必要がある。

In [24]:
cv2.add(x_image, y_image, dtype=cv2.CV_8U)

array([[255],
       [  0],
       [  0],
       [  0]], dtype=uint8)

何も指定しないとfloat64になって、255の限界などは特になく浮動小数点数として扱われる。

In [25]:
z_image = cv2.add(x_image, y_image)
print(z_image)
print(z_image.dtype)
print(z_image.shape)

[[260.]
 [  0.]
 [  0.]
 [  0.]]
float64
(4, 1)


自動的に4チャンネルの画像になってしまうのはなぜだろう? [ドキュメント](https://docs.opencv.org/4.x/d2/de8/group__core__array.html)と挙動が違う.